--DDL_EX_1_1
CREATE DATABASE Exercicio_1_1;

USE Exercicio_1_1;

CREATE TABLE Pessoa
(
	IdPessoa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (25) NOT NULL,
	CNH CHAR (10) NOT NULL UNIQUE
)

CREATE TABLE Telefone
(
	IdTelefone INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa) NOT NULL,
	Numero VARCHAR (20) UNIQUE NOT NULL
)

CREATE TABLE Email
(
	IdEmail INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa) NOT NULL,
	endereco VARCHAR (35) UNIQUE NOT NULL
)

SELECT * FROM Pessoa
SELECT * FROM Telefone
SELECT * FROM Email


DROP TABLE Pessoa;