--DDL_EX_1_2
CREATE DATABASE Exercicio_1_2;
 
 USE Exercicio_1_2;

 CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (25) NOT NULL,
)

 CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (25) NOT NULL,
)

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (25) NOT NULL UNIQUE,
)

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (25) NOT NULL,
)

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	Placa char(10) UNIQUE NOT NULL
)

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	Idveiculo INT FOREIGN KEY REFERENCES Veiculo(Idveiculo) NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	valor FLOAT NOT NULL,
	DataInicial DATE NOT NULL,
	DataFinal DATE NOT NULL 
)

DROP TABLE Aluguel